spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/chinook
        username: postgres
        password: pass
    jpa:
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    mvc:
        hiddenmethod:
            filter:
                enabled: true